### ISSUE TITLE
UI doesn't appear

### ISSUE THREAD

**Issue by BrentW89** [kinsi55/BeatSaber_BetterSongSearch#10]
I installed the latest version in mod assistant and the prerequisites from Modassistance:
SongDetailsCache
BeatSaberMarkupLanguage 
SongCore

But the UI elements in the pictures does not show up. I have custom songs appearing so that works.

I then downloaded the latest 0.70 version here and pasted in the DLL over the older one from Modassistant but that didn't work either. Any idea what's wrong?

**Comment by kinsi55** [comment]
Can you attach the _lastest.log from your Logs folder?

**Comment by BrentW89** [comment]
Here it is:
[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongSearch/files/8198913/_latest.log)

**Comment by BrentW89** [comment]
The file is dated from this morning when I last played and I got it from:
C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Logs
after finding the path via a button in Mod Assistant.

I have a list of custom songs, favorited songs (hearts), and the ability to search or filter somewhat, but no sorting (I'd like to see the newest songs I've downloaded at top and create different playlists at a minimum)

Other than that, I can't say I've seen any other mods have an effect. I had to reinstall Windows when I moved to a new machine and restored my Beatsaber folders from a backup, so maybe a registry setting or something got lost?  What would you suggest? I don't want to lose my 200-300 songs I painstakingly curated and preferrably not my high scores if I can avoid it.

Thank you!
