### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Jordankcarney** [kinsi55/BeatSaber_BetterSongSearch#11]
A

**Comment by kinsi55** [comment]
Thanks for voicing your negative opinion towards my work that works reasonably well and you can use for free - Unfortunately you failed to provide any information that I can use to actually improve this - Specific examples that dont work as expected would have been much more useful.

Besides that, seeing as you seem to be a dev yourself, feel free to suggest specific things to improve while keeping in mind it should have low execution time: https://github.com/kinsi55/BeatSaber_BetterSongSearch/blob/master/Util/WeightedSongSearch.cs#L14-L125

**Comment by Jordankcarney** [comment]
You're right. I was very frustrated when I posted this for no good reason and this was not the place to voice a complaint like this or in this manner. 

My apologies.

**Comment by kinsi55** [comment]
I have realized a flaw in my logic when trying to match partical song authors changed it up a bit. Give this a try and let me know if this more consistently results in what you'd expect.

[BetterSongSearch.zip](https://github.com/kinsi55/BeatSaber_BetterSongSearch/files/8296705/BetterSongSearch.zip)

**Comment by kinsi55** [comment]
@Jordankcarney
