### ISSUE TITLE
I'm going to play with this Beat Saber mode and there's nothing on the left or setting up that mode like I don't have it

### ISSUE THREAD

**Issue by GabGuz** [kinsi55/BeatSaber_BetterSongSearch#13]
I have a photo of this : ![image](https://user-images.githubusercontent.com/103215570/167267205-9ad755d9-be1f-42e3-bd96-94546c2a87df.png)

**Comment by kinsi55** [comment]
Seems like your mods just dont work at all in general. See the BSMG Discord for help: https://discord.gg/beatsabermods

**Comment by GabGuz** [comment]
I have mod : 
![image](https://user-images.githubusercontent.com/103215570/167267284-1fe5cbe6-2e29-47f6-b75a-0cb3be228c7f.png)

**Comment by kinsi55** [comment]
If this is all you have thats not going to work as you are missing other things Better Song Search depends on: https://github.com/kinsi55/BeatSaber_BetterSongSearch#requirements

The easiest way to grab everything you need is to just use Modassistant.
