### ISSUE TITLE
Downloads Failing

### ISSUE THREAD

**Issue by BreRex13** [kinsi55/BeatSaber_BetterSongSearch#14]
Hello,

I am not a coder and don't know how to check the logs in Better Song Search when downloads fail. Downloads were working fine yesterday and have been failing today. I restarted my computer and it didn't help. Not sure what else to try or do. Any help would be greatly appreciated.

Thanks!

**Comment by kinsi55** [comment]
Are you on the latest version which I have releases yesterday? https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases/tag/v0.7.69

**Comment by BreRex13** [comment]
> Are you on the latest version which I have released yesterday? https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases/tag/v0.7.69

Swapped out the old .dll for the new one. That was the ticket! Works flawlessly again. Thank you SO much!

**Comment by kinsi55** [comment]
Thank you too. It just not working *some times* for a small percent of people was one of the things I was trying to address with that update - Good to hear that it seems to have done it 👍
