### ISSUE TITLE
[Feature Request] Auto compiling via Github Actions

### ISSUE THREAD

**Issue by fred913** [kinsi55/BeatSaber_BetterSongSearch#16]
I suggest trying Github Actions that allows a more geek chance for development usages. It'll be easier to develop my mod fork, with location-specific features.

**Comment by kinsi55** [comment]
Setting that up is not extremely straight forward and I dont really need it so I didnt bother.

That being said, whats your fork? Maybe it could just be implemented in base?

**Comment by fred913** [comment]
Apologies for the delayed response.
Regarding my initial intention for the fork, I had aimed to incorporate supplementary mirror sites of the accessed platforms, with the purpose of enhancing network efficiency in specific regions plagued by inadequate global connectivity.
However, I have been informed by my friend that this feature has already been integrated into the base version ("Use Chinese BeatSaver Mirror"), rendering the purpose of my fork ended.
