### ISSUE TITLE
Better Instructions

### ISSUE THREAD

**Issue by Oh4sh0** [kinsi55/BeatSaber_BetterSongSearch#17]
Installation:
"You can always find the latest download in [The Releases](https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases), simply drag the files into the respective folders"

Where does one find the "respective folders" --I'm sure I'll find it, but would be nice if they were just listed here.

**Comment by kinsi55** [comment]
In case of a dll, simply into the Plugins folder (This ofc assumes that your game is already mod-ready). This is rather common "modding knowledge" so I dont really go in depth about that sorry.
