### ISSUE TITLE
[Feature Request] Filter by BeatSaver tags

### ISSUE THREAD

**Issue by PulseLane** [kinsi55/BeatSaber_BetterSongSearch#19]
Ability to search by the BeatSaver tags would be quite pog :D

**Comment by kinsi55** [comment]
I'll need to figure out some way to compress the beatsaver tags into the songdetails dataset at some point - Unfortunately theres too many to just do an int32 bitflag

**Comment by kinsi55** [comment]
Its been a while, I got a burst of motivation and this is now happening soon :P

**Comment by kinsi55** [comment]
https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases/tag/v0.8.0 👍
