### ISSUE TITLE
Scroll hack for filter view

### ISSUE THREAD

**Issue by Futuremappermydud** [kinsi55/BeatSaber_BetterSongSearch#2]
https://github.com/kinsi55/BeatSaber_BetterSongSearch/blob/master/UI/SongListController.cs#L183-L191 
This should be moved to flow coordinator so that other view controllers are affected. Currently filter drop downs do not scroll

**Comment by kinsi55** [comment]
Can you even scroll dropdowns with the Joystick normally? I believe having tested that before (Hence the commented out lines) and came to the conclusion that either, that isnt possible, or that this implementation doesnt work for that and something more involved would be needed

**Comment by Futuremappermydud** [comment]
Weird, it should scroll. Maybe apply the same hack used for sort dropdown for the other filters? So that it’s easier

**Comment by Futuremappermydud** [comment]
I applied it to the quest port and it works just fine  ¯\_(ツ)_/¯
https://github.com/Christoffyw/BetterSongSearchQuest/blob/ui-testing/src/UI/ViewControllers/SongList.cpp#L503-L514

**Comment by kinsi55** [comment]
I'll try to not forgor / test it for next update

**Comment by kinsi55** [comment]
A global resources call for this is super hacky. I'd classifly this as a BSML bug and see if fixing it there makes more sense. Until then this is closed for now.
