### ISSUE TITLE
Minimum Upload Date is June 2018

### ISSUE THREAD

**Issue by Auros** [kinsi55/BeatSaber_BetterSongSearch#20]
You can't set the minimum upload date to anything before June of 2018, so any maps uploaded in May of 2018 cannot be viewed.

![image](https://user-images.githubusercontent.com/41306347/215977999-b162b7a2-4412-4f7f-921b-8cce32448896.png)

**Comment by kinsi55** [comment]
I think this might just be a visual bug, I'll fix nontheless (In code minimum / first value is 1. May)

![grafik](https://user-images.githubusercontent.com/8348306/216119100-19d95c0d-7908-4274-a1f9-d13b33d38785.png)

**Comment by kinsi55** [comment]
Yeah as long as you do not touch the date slider it is only visual - Only when you change it it actually applies
