### ISSUE TITLE
No songs showing when searching

### ISSUE THREAD

**Issue by m4t7w** [kinsi55/BeatSaber_BetterSongSearch#23]
Hello, i have installed the lastest version and the mod is loading correctly, but when i go to the search menù no songs are showing and i cannot search/download anything.

I tryed running with the debug menu and i got this error: [ERROR @ 22:45:51 | BeatSaver Downloader] System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (Unable to establish connection. Persistent rejection of the target computer.

I also have all other dependencies up to date, i don't know where is the problem.

**Comment by kinsi55** [comment]
The error that you shared is, as stated, from BeatSaver Downloader - Not from Better Song Search

That being said, it sounds like *something* is preventing you from connecting to BeatSaver, so its beyond the scope of this or that plugin.

**Comment by m4t7w** [comment]
Yeah sorry, that is from beatsaver downloader, this other is from your plugin (from where i click the bettersearch button to the menu)

[CRITICAL @ 23:47:11 | UnityEngine] SocketException: Unable to establish connection. Persistent rejection of the target computer.
[CRITICAL @ 23:47:11 | UnityEngine] System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () (at <cb1c94a571d140989f59bc38dfed683a>:0)
[CRITICAL @ 23:47:11 | UnityEngine] System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) (at <cb1c94a571d140989f59bc38dfed683a>:0)
[CRITICAL @ 23:47:11 | UnityEngine] System.Net.WebConnection+<>c.<Connect>b__16_1 (System.IAsyncResult asyncResult) (at <cb1c94a571d140989f59bc38dfed683a>:0)
[CRITICAL @ 23:47:11 | UnityEngine] System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) (at <75633565436c42f0a6426b33f0132ade>:0)
[CRITICAL @ 23:47:11 | UnityEngine] --- End of stack trace from previous location where exception was thrown ---
[CRITICAL @ 23:47:11 | UnityEngine] System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) (at <cb1c94a571d140989f59bc38dfed683a>:0)
[CRITICAL @ 23:47:11 | UnityEngine] Rethrow as WebException: Error: ConnectFailure (Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
[CRITICAL @ 23:47:13 | UnityEngine] AuthenticationException: Failed to retrieve an AuthenticationToken for Platform Steam
[CRITICAL @ 23:47:13 | UnityEngine] PlatformAuthenticationTokenProvider.GetAuthenticationToken () (at <ea98a39846ee4397a2312eb4797daf20>:0)
[CRITICAL @ 23:47:13 | UnityEngine] BeatLeader.API.Authentication.PlatformTicket () (at <8b37b0bcbf59432a92f2b33f2bcb3abc>:0)
[CRITICAL @ 23:47:13 | UnityEngine] Rethrow as AggregateException: One or more errors occurred. (Failed to retrieve an AuthenticationToken for Platform Steam)
[CRITICAL @ 23:47:13 | UnityEngine] System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <75633565436c42f0a6426b33f0132ade>:0)
[CRITICAL @ 23:47:13 | UnityEngine] System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <75633565436c42f0a6426b33f0132ade>:0)
[CRITICAL @ 23:47:13 | UnityEngine] System.Threading.Tasks.Task`1[TResult].get_Result () (at <75633565436c42f0a6426b33f0132ade>:0)
[CRITICAL @ 23:47:13 | UnityEngine] BeatLeader.API.Authentication+<DoLogin>d__11.MoveNext () (at <8b37b0bcbf59432a92f2b33f2bcb3abc>:0)
[CRITICAL @ 23:47:13 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <684fd32169ff40798327c75e99cfb4f0>:0)

>it sounds like something is preventing you from connecting to BeatSaver

What do you mean? I tried adding a rule in firewall to beat saber, still not working. From this logs it seems like it cannot get the steam auth token even though i purchased it... There's a way to enter it manually or link steam account?

**Comment by kinsi55** [comment]
The retrieval of the platform ticket likely fails because of that same underlying reason: For some reason all web access of your beat saber just fails. This is an error beyond the game & mods, what it is tho, I can't tell you

**Comment by m4t7w** [comment]
I identified the cause: it was an option in my modem settings (strange that it affected only beat saber). Now it's all working fine, your mod and others too. Sorry for waisting your time

**Comment by kinsi55** [comment]
No worries, glad you figured it out!
