### ISSUE TITLE
Song filters still appear after pressing play

### ISSUE THREAD

**Issue by xFutuxe** [kinsi55/BeatSaber_BetterSongSearch#3]
After downloading a song and pressing play on song details the search filters remain active 

![image](https://user-images.githubusercontent.com/65718499/134783579-e201ea1c-67ff-48a5-9af3-2e26760e5e27.png)

**Comment by kinsi55** [comment]
Is this on 1.18?

**Comment by xFutuxe** [comment]
Yes

**Comment by kinsi55** [comment]
I'm unable to reproduce that, can you start the game, reproduce the bug, close the game and attach your _latest.log from your logs folder?

**Comment by xFutuxe** [comment]
added issue to wrong repo at start sorry about that lol

**Comment by xFutuxe** [comment]
Here 👍 

[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongSearch/files/7230248/_latest.log)

**Comment by kinsi55** [comment]
Seems to be a regression due to changes in BSML. I'll talk with the person who did those

**Comment by xFutuxe** [comment]
👍

**Comment by kinsi55** [comment]
This is fixed in the upcoming update for BeatSaberMarkupLanguage (BSML), ty for the report
