### ISSUE TITLE
Preview song 

### ISSUE THREAD

**Issue by jasonkinly** [kinsi55/BeatSaber_BetterSongSearch#5]
Clicking on the song did not hear the 10-second preview of the corresponding song, so I can only download it directly, I don’t know if it’s the song I want

**Comment by WGzeyu** [comment]
BeatSaver provides `previewURL` in the API, the address format is: `https://cdn.beatsaver.com/[HASH].mp3`, which is basically a 10-second, very small preview file, which is suitable for this function.

**Comment by kinsi55** [comment]
Needing / wanting to preview songs which you have not downloaded yet imo is an extremely niche thing imo. I'll consider adding it for completeness but its not high prio.

**Comment by GabrielDuarteM** [comment]
@kinsi55 I see, yeah, it does make sense to also think about the usability of the feature. I think the preview on osu is actually the full quality song, and the youtube vid only showed a very low-quality music 😂 It was the only youtube video I found that actually showed the feature though

In any case, I'm not sure how it would behave in-game, if the delay would be too much to the point it gets weird... I suppose it would depend on the user's internet speed, but there are also other ways to implement it if it gets to that point, like with a button you have to press to listen to it, or with a toggle on the plugin settings that enable or disable automatic preview, and if the user doesn't like it, then it could be disabled...

I'd still think the usability would be better if you would click and get the preview, even if it takes a while to load. 
It's kind of a plus, you get more info about the song, as without it you wouldn't know for sure which music it is until you download it and select it on the music list menu, and with that feature, you get to listen to it beforehand, even if it takes some seconds to load on slower internet speeds (which most likely wouldn't apply if you have good internet). 

Also, I'd argue that being able to listen to the song is one of the most important pieces of information you need to know before downloading, along with the map quality (which you can already deduce today, by the like/dislike ratio)... Having that would save me a lot of time and storage by avoiding downloading music I dislike :)

**Comment by Chicken-Bones** [comment]
Yes! I'd like to listen to a popular map I don't recognise the song name of to see if it might be a bop, I don't mind if there's ~5s before it starts to play.

**Comment by WGzeyu** [comment]
> Yes! I'd like to listen to a popular map I don't recognise the song name of to see if it might be a bop, I don't mind if there's ~5s before it starts to play.

It's not as long as 5 seconds, it should be about 0.5 seconds

**Comment by kinsi55** [comment]
Totally forgot about this, I'll try to look into it soon

**Comment by kinsi55** [comment]
Will be added in the next release 👍
