### ISSUE TITLE
dont see better song search

### ISSUE THREAD

**Issue by glikris** [kinsi55/BeatSaber_BetterSongSearch#6]
forgive me if this isnt the correct place to be asking but im not able to see better song search in the list of mods. i downgraded to 1.16.2 to be able to play customs with a friend and "more songs" doesnt work in that version. (idk if just me and the friend or if thats a known thing) so we have to manually download songs and move them over which isnt the biggest deal but would be nice to be able to download inside the game. do i need to remove the mod for "more songs" for bettersongsearch to work? i have the 3 requirements and its for sure in the correct plugins folder and also im using version 0.0.2 since its the one that showed up in beatsabermoddinggroup for 1.16.2. would appreciate any insight

**Comment by kinsi55** [comment]
You need to use Version 0.5.5, versions past that only work on 1.17.1 and above

https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases/tag/v0.5.5

**Comment by glikris** [comment]
ah so bettersongsearch just isnt usable on 1.16.2 at all?

**Comment by kinsi55** [comment]
It is, if you use that specific version that I linked. Versions after that do not work.

**Comment by glikris** [comment]
oh i tried that one just now and im still not seeing it show up just moresongs and that one only shows question marks as album art and the download button is grayed out

**Comment by kinsi55** [comment]
Then some of your requirements arent correct. You can see the lowest versions that you need here: https://github.com/kinsi55/BeatSaber_BetterSongSearch/blob/master/manifest.json#L10-L13

**Comment by glikris** [comment]
i believe theyre correct :/  BSIPA is on 4.1.6, BeatSaberMarkupLanguage is on 1.5.3, SongDetailsCache is on 1.1.8, and SongCore is on 3.5.0 so im just not too sure but i wont bother you about it anymore i appreciate the help

**Comment by kinsi55** [comment]
take the _latest.log from your logs folder and attach it

**Comment by glikris** [comment]
ah ill try that then i dont think i did that manually i believe that was just clicking install or update on mod assistant

**Comment by kinsi55** [comment]
Must have done it manually, 1.1.8 SongDetailsCache is not in mod assistant for 1.16.2. Either way, if you fix that it should work 👍

**Comment by glikris** [comment]
![Movies   TV 10_5_2021 7_34_51 PM](https://user-images.githubusercontent.com/91894239/136116945-da39cb68-83c1-4186-a0f1-cefeb68b72d2.png)
![Movies   TV 10_5_2021 7_34_34 PM](https://user-images.githubusercontent.com/91894239/136116948-2d6f8379-6ca6-44e4-8a50-df097e2b775e.png)

i moved the songdetailscache dll to libs and the manifest to plugins and still nothing. is there a max number of mods that can show up to the left? it seems like if its following that specific 3x7 grid that it wouldnt have space to show it but ive never thought about that before
 
[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongSearch/files/7289829/_latest.log)

thats the log file for that instance if you still feel like looking through it

**Comment by kinsi55** [comment]
`[WARNING @ 19:32:39 | IPA/Loader] SongDetailsCache is missing dependency protobuf-net@^3.0.102`

you missed the protobuf dependency needed for SongDetailsCache ;)

But that being said, yes there is a limit, if theres no more room for buttons, thats it, but you seem to have another row left before you reach that *eventho i gotta say that is way too many plugins*

**Comment by kinsi55** [comment]
You can get it from ModAssistant, or manually from beatmods.com - the site behind ModAssistant

**Comment by glikris** [comment]
didnt even think to check there. looking at it though shows i have it at v3.0.102
