### ISSUE TITLE
Special Characters missing on Search Keyboard

### ISSUE THREAD

**Issue by AlluringKoala** [kinsi55/BeatSaber_BetterSongSearch#9]
https://user-images.githubusercontent.com/75051674/156966663-dae94b11-4187-4472-9be5-6ea5a0a6cb30.PNG
This is the keyboard that I want because songs like Camellia- t/a/n/a/s/i/n/n is imposable to type

**Comment by kinsi55** [comment]
This is not directly obvious of course but wherever there would be a character that does not exist on the basegame keyboard you can just impose a space. This works for most of the cases
![Beat_Saber_2022-03-07_10-53-34](https://user-images.githubusercontent.com/8348306/157008438-77b337dd-9030-46e2-9799-5adfbd1b8786.png)

**Comment by kinsi55** [comment]
My solution to this problem is now implemented in the latest update :)
